#!/bin/bash
set -e

# Execute the init SQL script using psql
psql -v ON_ERROR_STOP=1 <<-EOSQL
CREATE USER $POSTGRES_USER WITH PASSWORD $POSTGRES_PASSWORD;
CREATE DATABASE $POSTGRES_DB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
-- Use $POSTGRES_DB database
\c $POSTGRES_DB
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Create schemas
CREATE SCHEMA main;
-- TODO: Create Tables
EOSQL
